apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: {{ .Values.fqdn | replace "." "-" }}-blog
  name: {{ .Values.fqdn | replace "." "-" }}-blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.fqdn | replace "." "-" }}-blog
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.fqdn | replace "." "-" }}-blog
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Values.fqdn | replace "." "-" }}-blog
            topologyKey: "kubernetes.io/hostname"
      containers:
        - image: storjlabs/blog:{{ .Values.docker_image_tag }}
          imagePullPolicy: Always
          name: www
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
