backend:
  name: github
  repo: storj/community-website
  branch: master
  base_url: https://community.staging.storj.io
  auth_endpoint: /oauth/auth

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "business"
    label: "Business posts"
    folder: "content/post/business"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false }
      - {label: "Category", name: "categories", widget: "list", default: ['business', ]}
      - {label: "Author", name: "authors", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "engineering"
    label: "Engineering posts"
    folder: "content/post/engineering"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false }
      - {label: "Category", name: "categories", widget: "list",default: ['engineering', ]}
      - {label: "Author", name: "authors", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "support"
    label: "Support posts"
    folder: "content/post/support"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false }
      - {label: "Category", name: "categories", widget: "list",default: ['support', ]}
      - {label: "Author", name: "authors", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "tokens"
    label: "Token posts"
    folder: "content/post/tokens"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false }
      - {label: "Category", name: "categories", widget: "list",default: ['tokens', ]}
      - {label: "Author", name: "authors", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "tutorials"
    label: "Tutorial posts"
    folder: "content/post/tutorials"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false }
      - {label: "Category", name: "categories", widget: "list",default: ['tutorials', ]}
      - {label: "Author", name: "authors", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
